name: Deploy Infrastructure

on:
  push:
    branches:
      - feature/*
      - current
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Environment Variables
        id: set-vars

        run: |
          COMMIT_HASH_SHORT=$(git rev-parse --short HEAD)
          echo "COMMIT_HASH_SHORT=${COMMIT_HASH_SHORT}" >> .env

          case "${GITHUB_REF#refs/heads/}" in
            feature/*)
              TAG=sandbox
              ;;
            current)
              TAG=sandbox
              ;;
            # develop)
            #   TAG=dev
            #   ;;
            # qa)
            #   TAG=qa
            #   ;;
            # uat)
            #   TAG=uat
            #   ;;
            main)
              TAG=latest
              ;;
          esac

          echo "DOCKER_IMAGE_TAG=${TAG}" >> .env
          echo "TF_PLUGIN_TIMEOUT=60s" >> .env

      - name: Upload .env file
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: .env

      - name: Log envs
        run: |
          source .env

          echo "COMMIT_HASH_SHORT=$COMMIT_HASH_SHORT"
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG"
          echo "TF_PLUGIN_TIMEOUT=$TF_PLUGIN_TIMEOUT"

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: setup

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PLATFORMS: linux/amd64,linux/arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download .env file
        uses: actions/download-artifact@v3
        with:
          name: env-file
          path: .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login docker.io -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and push Docker image

        env:
          COMMIT_HASH_SHORT: ${{ env.COMMIT_HASH_SHORT }}
          DOCKER_IMAGE_TAG: ${{ env.DOCKER_IMAGE_TAG }}

        run: |
          source .env

          echo "COMMIT_HASH_SHORT=${COMMIT_HASH_SHORT}"
          echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}"

          docker buildx build --platform $PLATFORMS -f Dockerfile.deploy -t docker.io/$DOCKER_USERNAME/vuejs-test:${COMMIT_HASH_SHORT} -t docker.io/$DOCKER_USERNAME/vuejs-test:${DOCKER_IMAGE_TAG} --push .
